//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Enrollment.MatriculaWSReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatriculaWSReference.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Login(string correo, string passwordhashed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LoginAsync(string correo, string passwordhashed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistrarUsuario(string Nombre, string Apellido1, string Apellido2, string Correo, string Telefono, string Cedula, int Rol, int Direccion, string PasswordHashed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(string Nombre, string Apellido1, string Apellido2, string Correo, string Telefono, string Cedula, int Rol, int Direccion, string PasswordHashed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable SelectUsuario(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> SelectUsuarioAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CursosMatricular", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CursosMatricular(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CursosMatricular", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> CursosMatricularAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GruposDeCurso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GruposDeCurso(int idCurso, string codigoPeriodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GruposDeCurso", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GruposDeCursoAsync(int idCurso, string codigoPeriodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HorarioGrupo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HorarioGrupo(int idGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HorarioGrupo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HorarioGrupoAsync(int idGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDireccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistrarDireccion(int codigoPostal, string detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDireccion", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegistrarDireccionAsync(int codigoPostal, string detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CodigosPostales", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CodigosPostales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CodigosPostales", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> CodigosPostalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MatricularGrupo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int MatricularGrupo(int codigoGrupo, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MatricularGrupo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MatricularGrupoAsync(int codigoGrupo, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HistorialCursos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable HistorialCursos(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HistorialCursos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> HistorialCursosAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HistorialGruposProfesor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable HistorialGruposProfesor(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HistorialGruposProfesor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> HistorialGruposProfesorAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstudiantesEnGrupo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EstudiantesEnGrupo(int codigoGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstudiantesEnGrupo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> EstudiantesEnGrupoAsync(int codigoGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarNota", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ActualizarNota(int codigoGrupo, string emailEstudiante, int nota, string estado, string comentarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarNota", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ActualizarNotaAsync(int codigoGrupo, string emailEstudiante, int nota, string estado, string comentarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MatricularCarrera", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int MatricularCarrera(int codigoCarrera, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MatricularCarrera", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MatricularCarreraAsync(int codigoCarrera, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCarreras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListarCarreras();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarCarreras", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarCarrerasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : Easy_Enrollment.MatriculaWSReference.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<Easy_Enrollment.MatriculaWSReference.ServicioWebSoap>, Easy_Enrollment.MatriculaWSReference.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Login(string correo, string passwordhashed) {
            return base.Channel.Login(correo, passwordhashed);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string correo, string passwordhashed) {
            return base.Channel.LoginAsync(correo, passwordhashed);
        }
        
        public int RegistrarUsuario(string Nombre, string Apellido1, string Apellido2, string Correo, string Telefono, string Cedula, int Rol, int Direccion, string PasswordHashed) {
            return base.Channel.RegistrarUsuario(Nombre, Apellido1, Apellido2, Correo, Telefono, Cedula, Rol, Direccion, PasswordHashed);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(string Nombre, string Apellido1, string Apellido2, string Correo, string Telefono, string Cedula, int Rol, int Direccion, string PasswordHashed) {
            return base.Channel.RegistrarUsuarioAsync(Nombre, Apellido1, Apellido2, Correo, Telefono, Cedula, Rol, Direccion, PasswordHashed);
        }
        
        public System.Data.DataTable SelectUsuario(string correo) {
            return base.Channel.SelectUsuario(correo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> SelectUsuarioAsync(string correo) {
            return base.Channel.SelectUsuarioAsync(correo);
        }
        
        public System.Data.DataTable CursosMatricular(string correo) {
            return base.Channel.CursosMatricular(correo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> CursosMatricularAsync(string correo) {
            return base.Channel.CursosMatricularAsync(correo);
        }
        
        public System.Data.DataTable GruposDeCurso(int idCurso, string codigoPeriodo) {
            return base.Channel.GruposDeCurso(idCurso, codigoPeriodo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GruposDeCursoAsync(int idCurso, string codigoPeriodo) {
            return base.Channel.GruposDeCursoAsync(idCurso, codigoPeriodo);
        }
        
        public string HorarioGrupo(int idGrupo) {
            return base.Channel.HorarioGrupo(idGrupo);
        }
        
        public System.Threading.Tasks.Task<string> HorarioGrupoAsync(int idGrupo) {
            return base.Channel.HorarioGrupoAsync(idGrupo);
        }
        
        public int RegistrarDireccion(int codigoPostal, string detalle) {
            return base.Channel.RegistrarDireccion(codigoPostal, detalle);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarDireccionAsync(int codigoPostal, string detalle) {
            return base.Channel.RegistrarDireccionAsync(codigoPostal, detalle);
        }
        
        public System.Data.DataTable CodigosPostales() {
            return base.Channel.CodigosPostales();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> CodigosPostalesAsync() {
            return base.Channel.CodigosPostalesAsync();
        }
        
        public int MatricularGrupo(int codigoGrupo, string correo) {
            return base.Channel.MatricularGrupo(codigoGrupo, correo);
        }
        
        public System.Threading.Tasks.Task<int> MatricularGrupoAsync(int codigoGrupo, string correo) {
            return base.Channel.MatricularGrupoAsync(codigoGrupo, correo);
        }
        
        public System.Data.DataTable HistorialCursos(string correo) {
            return base.Channel.HistorialCursos(correo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> HistorialCursosAsync(string correo) {
            return base.Channel.HistorialCursosAsync(correo);
        }
        
        public System.Data.DataTable HistorialGruposProfesor(string correo) {
            return base.Channel.HistorialGruposProfesor(correo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> HistorialGruposProfesorAsync(string correo) {
            return base.Channel.HistorialGruposProfesorAsync(correo);
        }
        
        public System.Data.DataTable EstudiantesEnGrupo(int codigoGrupo) {
            return base.Channel.EstudiantesEnGrupo(codigoGrupo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EstudiantesEnGrupoAsync(int codigoGrupo) {
            return base.Channel.EstudiantesEnGrupoAsync(codigoGrupo);
        }
        
        public int ActualizarNota(int codigoGrupo, string emailEstudiante, int nota, string estado, string comentarios) {
            return base.Channel.ActualizarNota(codigoGrupo, emailEstudiante, nota, estado, comentarios);
        }
        
        public System.Threading.Tasks.Task<int> ActualizarNotaAsync(int codigoGrupo, string emailEstudiante, int nota, string estado, string comentarios) {
            return base.Channel.ActualizarNotaAsync(codigoGrupo, emailEstudiante, nota, estado, comentarios);
        }
        
        public int MatricularCarrera(int codigoCarrera, string correo) {
            return base.Channel.MatricularCarrera(codigoCarrera, correo);
        }
        
        public System.Threading.Tasks.Task<int> MatricularCarreraAsync(int codigoCarrera, string correo) {
            return base.Channel.MatricularCarreraAsync(codigoCarrera, correo);
        }
        
        public System.Data.DataTable ListarCarreras() {
            return base.Channel.ListarCarreras();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarCarrerasAsync() {
            return base.Channel.ListarCarrerasAsync();
        }
    }
}
